name: CI

on:
  pull_request:
    branches: main

jobs:
  ci:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        with:
          globs: "**/*.md"

      - name: Actionlint
        uses: reviewdog/action-actionlint@8b682e1e7e512151d73a6b9449cbff173846226e  # v1.74.0
        with:
          fail_level: error

      - name: Yamllint
        uses: reviewdog/action-yamllint@6803b0dc8f295034a6156b924814053acb2e6f5a  # v1.24.0
        with:
          fail_level: error
